jwt:
  secret: notesecret
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  main:
    allow-circular-references: true
  datasource:
    password: Witch043
    url: jdbc:mysql://localhost:3306/noteapp
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 3535